### ISSUE TITLE
Small HTML syntax error

### ISSUE THREAD

**Issue by bruncsak** [abh/ntppool#204] opened 2021-07-03 14:42 UTC
There is a small syntax error in the file docs/manage/tpl/navigation_sidebar.html .
Two closing HTML tags (`</b>` and `</a>` ) are in incorrect order.

I created a pull request to fix this: https://github.com/abh/ntppool/pull/203

**Comment by tnhung2011** [comment] 2024-11-07 11:52
I can see that the issue is resolved at https://github.com/abh/ntppool/pull/203. Can anyone please close this?

**Closed** 2024-11-07 12:37 UTC
